language: scala
jdk: oraclejdk8

env:
  global:
    - SBT_OPTS="-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:MetaspaceSize=256M -XX:MaxMetaspaceSize=512M -Xmx2G"
    - SBT_GHPAGES_COMMIT_MESSAGE='Publishing Scaladoc [ci skip]'


script:
  - sbt checkFormat clean coverage +test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      sbt updateImpactSubmit coverageReport coverageAggregate codacyCoverage
      /bin/bash <(wget --quiet https://codecov.io/bash)
      git config --global user.email "pathikritbhowmick@msn.com"
      git config --global user.name "circle-ci"
      git config --global push.default simple
      mkdir ~/.ssh && ssh-keyscan github.com > ~/.ssh/known_hosts
      sbt ghpagesPushSite +publish
    fi

cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
  - $HOME/.m2

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
  